"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sketchfab (https://sketchfab.com/Sketchfab)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/where-is-the-sketchfab-team-0ff2bb7d8f0c4f04a8d09cfaf842fbf2
Title: Where is the Sketchfab team?
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";


function WorldEarthPlanet({ props }: any) {
  const { nodes, materials } = useGLTF("whiteEarth.glb");
  const groupRef = useRef<any>();

  // Actualiza la rotación en cada renderizado
  useFrame(() => {
    if (groupRef.current) {
      // Ajusta la velocidad y el eje de rotación según sea necesario
      groupRef.current.rotation.y += 0.001;
    }
  });

  return (
    <group position={[1,-0.2,0]} ref={groupRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.557}>
        <mesh
          geometry={nodes.Sphere002_0.geometry}
          material={materials.land}
          rotation={[0, 0, -Math.PI / 2]}
          scale={1.003}
        />
        <mesh
          geometry={nodes.Sphere_0.geometry}
          material={materials.water}
          rotation={[0, 0, -Math.PI / 2]}
        />
      </group>
    </group>
  );
  
}

useGLTF.preload("whiteEarth.glb");

export default WorldEarthPlanet;
